apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components-appset-crd
spec:
  generators:
  - git:
      repoURL: https://github.com/SaschaJohn/argocdtest
      revision: main
      directories:
      - path: argocd
      - path: kyverno
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/SaschaJohn/argocdtest
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true