apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components-appset-crd
spec:
  generators:
  - git:
      repoURL: https://github.com/SaschaJohn/argocdtest
      revision: main
      directories:
      - path: core/*
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/SaschaJohn/argocdtest
        targetRevision: main
        path: '{{path}}'
        plugin: 
          name: kustomize-build-with-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true