apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-components-appset-crd
spec:
  generators:
  - git:
      repoURL: https://github.com/SaschaJohn/argocdtest
      revision: main
      directories:
      - path: argo
  template:
    metadata:
      name: 'argocd'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/SaschaJohn/argocdtest
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        preserveResourcesOnDeletion: true 
        syncOptions:
          - "Cascade=false"
